### ISSUE TITLE
Author Profile block for article pages

### ISSUE THREAD

**Issue by mhaack** [urfuwo/hlx-test#119] opened 2024-02-12 09:43 UTC
See [Figma](https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=891-41380&mode=design&t=3FBBy6sZRrnPwp4Q-4)

![Screenshot 2024-02-12 at 10 42 33](https://github.com/urfuwo/hlx-test/assets/2643450/65e4315f-7cdb-48b9-beb9-e4b9630490a0)

**Comment by pahupe** [comment] 2024-02-22 07:27
This seems to be a duplicate of #148, wdyt @benpeter and @mhaack ? Or shall we do a ticket for a single L3 author profile and a separate ticket for author profile list?

**Comment by pahupe** [comment] 2024-02-22 08:00
@mhaack : But would we not simply create one "Author Profile" block, and if the editors provide an author name, then lookup that author => index, otherwise lookup the author(s) in the page metadata => index?

I was just wondering, as the designers call both elements "Author Profile".

**Comment by mhaack** [comment] 2024-02-22 08:16
> Ok, I'll pick this one, and once we have progressed, we can see how much can be reused in https://github.com/urfuwo/hlx-test/issues/148
👍 yes let do it like this. I think #148 covers more used cases (multiple cards, different card items) but can extend from what we have.

**Comment by mhaack** [comment] 2024-02-22 08:17
> Ok, I'll pick this one, and once we have progressed, we can see how much can be reused in https://github.com/urfuwo/hlx-test/issues/148
👍 yes let do it like this. I think #148 covers more used cases (multipe cards, different card items) but can extend from what we have.

**Closed** 2024-02-29 10:52 UTC
Labels: L3
